language: node_js
node_js:
  - "node"
install: 
  - npm install mysql

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

jobs:
  include:
    - script:
        - node app.js & firefox localhost:3000 # start a Web server
        # give Web server some time to bind to sockets, etc



