language: node_js
node_js:
  - "node"
install:
  - npm install mysql
  - npm install ejs

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

jobs:
  include:
    - script:
        - node test.js # start a Web server
    -script:
        - node ./functiontests/functiontesting.js
        - node ./functiontests/functioncleanup.js



